title: IF BIO ART LAB
description: A documentation and resource site for Invisible Flock's Bio Art LAb
theme: just-the-docs

url: https://beniflock.github.io/IF_BIO_ART_LAB

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
